<template>
<v-col style="align-self: center;">


    <v-row style="align: center;">
        <v-col cols="4" style="align-self: center;">
        <v-img
        lazy-src="https://picsum.photos/id/11/10/6"
        max-height="150"
        max-width="250"
        src="https://picsum.photos/id/11/500/300"
        ></v-img>
        <v-row>
            <v-card-title class="text-h5">
              Libro -1. 
            </v-card-title>
        </v-row>

    </v-col>

    <v-col cols="4" style="align-self: center;">
        <v-img
        lazy-src="https://picsum.photos/id/11/10/6"
        max-height="150"
        max-width="250"
        src="https://picsum.photos/id/11/500/300"
        ></v-img>
        <v-row>
            <v-card-title class="text-h5">
              Libro -2. 
            </v-card-title>
        </v-row>

    </v-col>
    

    <v-col cols="4" style="align-self: center;">
        <v-img
        lazy-src="https://picsum.photos/id/11/10/6"
        max-height="150"
        max-width="250"
        src="https://picsum.photos/id/11/500/300"
        ></v-img>
        <v-row>
            <v-card-title class="text-h5">
              Libro -3. 
            </v-card-title>
        </v-row>

    </v-col>
        
    </v-row>

    <v-row style="align: center;">
        <v-col cols="4" style="align-self: center;">
        <v-img
        lazy-src="https://picsum.photos/id/11/10/6"
        max-height="150"
        max-width="250"
        src="https://picsum.photos/id/11/500/300"
        ></v-img>
        <v-row>
            <v-card-title class="text-h5">
              Libro -1. 
            </v-card-title>
        </v-row>

    </v-col>

    <v-col cols="4" style="align-self: center;">
        <v-img
        lazy-src="https://picsum.photos/id/11/10/6"
        max-height="150"
        max-width="250"
        src="https://picsum.photos/id/11/500/300"
        ></v-img>
        <v-row>
            <v-card-title class="text-h5">
              Libro -2. 
            </v-card-title>
        </v-row>

    </v-col>
    

    <v-col cols="4" style="align-self: center;">
        <v-img
        lazy-src="https://picsum.photos/id/11/10/6"
        max-height="150"
        max-width="250"
        src="https://picsum.photos/id/11/500/300"
        ></v-img>
        <v-row>
            <v-card-title class="text-h5">
              Libro -3. 
            </v-card-title>
        </v-row>

    </v-col>
        
    </v-row>
   
    <v-row style="align: center;">
        <v-col cols="4" style="align-self: center;">
        <v-img
        lazy-src="https://picsum.photos/id/11/10/6"
        max-height="150"
        max-width="250"
        src="https://picsum.photos/id/11/500/300"
        ></v-img>
        <v-row>
            <v-card-title class="text-h5">
              Libro -1. 
            </v-card-title>
        </v-row>

    </v-col>

    <v-col cols="4" style="align-self: center;">
        <v-img
        lazy-src="https://picsum.photos/id/11/10/6"
        max-height="150"
        max-width="250"
        src="https://picsum.photos/id/11/500/300"
        ></v-img>
        <v-row>
            <v-card-title class="text-h5">
              Libro -2. 
            </v-card-title>
        </v-row>

    </v-col>
    

    <v-col cols="4" style="align-self: center;">
        <v-img
        lazy-src="https://picsum.photos/id/11/10/6"
        max-height="150"
        max-width="250"
        src="https://picsum.photos/id/11/500/300"
        ></v-img>
        <v-row>
            <v-card-title class="text-h5">
              Libro -3. 
            </v-card-title>
        </v-row>

    </v-col>
        
    </v-row>


</v-col>

  </template>